export default [
  { nickname: 'Андрей' },
  { nickname: 'Балагур' },
  { nickname: 'Владимир Юрьев' },
  { nickname: 'Григорий Мишин' },
  { nickname: 'Дама с Собачкой' },
  { nickname: 'Ерофей Павлович' },
  { nickname: 'Ёлкинс' },
  { nickname: 'Жорж' },
  { nickname: 'Зураб' },
  { nickname: 'Иван Иванович' },
  { nickname: 'Йых Пу' },
  { nickname: 'Клемент Ворошилов' },
  { nickname: 'Леля' },
  { nickname: 'Марат Мамедов' },
  { nickname: 'Нельсон' },
  { nickname: 'Оперуполномоченный по борьбе с плохо организованной преступностью' },
  { nickname: 'Пётр Петрович' },
  { nickname: 'Роберт Браун' },
  { nickname: 'Соломон Кацман' },
  { nickname: 'Таку Камаку' },
  { nickname: 'Удегей' },
  { nickname: 'Фёдор Фёдорович' },
  { nickname: 'Хосе Мария Родригес' },
  { nickname: 'Цапиков' },
  { nickname: 'Чалый' },
  { nickname: 'Шурочка' },
  { nickname: 'Щедрая Душа' },
  { nickname: 'Ыгын Выргун' },
  { nickname: 'Эмиль Морсо' },
  { nickname: 'Юрий Смирнов' },
  { nickname: 'Ярослава' },
]
